const programmersData = [
    {
        id: 01,
        name: 'Mahmudur Rahman',
        age: 27,
        country: 'Bangladesh',
        skill: 'MERN Developer',
        salary: 12099,
        image: 'https://thumbs.dreamstime.com/b/programmer-working-laptop-portrait-smiling-indian-programmer-working-laptop-office-desk-200015841.jpg',
    },
    {
        id: 02,
        name: 'Jonh Lew',
        age: 32,
        country: 'Netherlands',
        skill: 'Full Stact Developer',
        salary: 11500,
        image: 'https://www.sheknows.com/wp-content/uploads/2018/08/stylish-man-looking-at-computer_dkkljg.jpeg',
    },
    {
        id: 03,
        name: 'Michel Moreland',
        age: 37,
        country: 'Germany',
        skill: 'Javascript Developer',
        salary: 10799,
        image: 'https://media.istockphoto.com/photos/cheerful-young-programmer-looking-at-camera-while-working-at-his-picture-id1151967132?k=20&m=1151967132&s=612x612&w=0&h=9PtHF4qFQUj0ImULPY5vgN4-NQYZfwALlzuKQSRz3do=',
    },
    {
        id: 04,
        name: 'Olivia Kelly',
        age: 24,
        country: 'USA',
        skill: 'Backend Web Developer',
        salary: 14250,
        image: 'https://www.businessinsider.in/thumb.cms?msid=74466977&width=1200&height=900',
    },
    {
        id: 05,
        name: 'Salma Khatun',
        age: 21,
        country: 'Bangladesh',
        skill: 'React Developer',
        salary: 15000,
        image: 'https://t4.ftcdn.net/jpg/02/95/10/89/360_F_295108935_pUAWYHrwzT3QKsFXZmJsDBXl4emx9r5p.jpg',
    },
    {
        id: 06,
        name: 'Abbas Ali',
        age: 24,
        country: 'Pakistan',
        skill: 'Apps Managment',
        salary: 9800,
        image: 'https://thumbs.dreamstime.com/b/technology-remote-job-lifestyle-concept-happy-smiling-indian-man-laptop-computer-working-home-office-indian-man-192151051.jpg',
    },
    {
        id: 07,
        name: 'Feroz Mahmud',
        age: 28,
        country: 'Bangladesh',
        skill: 'Software Engineer',
        salary: 17500,
        image: 'https://thumbs.dreamstime.com/b/freelance-work-happy-millennial-indian-man-working-computer-home-office-sitting-desk-laptop-handsome-western-guy-203702597.jpg',
    },
    {
        id: 08,
        name: 'Paul Cutterwood',
        age: 51,
        country: 'UK',
        skill: 'Feontend Web Developer',
        salary: 11475,
        image: 'https://www.cheatsheet.com/wp-content/uploads/2016/05/Businessman-looking-at-his-laptop-in-disbelief-640x457.jpg',
    },
    {
        id: 09,
        name: 'Anita Sharma',
        age: 23,
        country: 'India',
        skill: 'HTML CSS',
        salary: 7599,
        image: 'https://www.forbesindia.com/media/wpower2020/Monika%20Shergill.jpg',
    },
    {
        id: 10,
        name: 'Developer Alam',
        age: 17,
        country: 'Bangladesh',
        skill: 'Problem Solving',
        salary: 21499,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlNfD5vlhqPnt64oh8A6R7YhBSSwxlEobWlw&usqp=CAU',
    },
    {
        id: 11,
        name: 'Programmer Jalil',
        age: 53,
        country: 'Bangladesh',
        skill: 'MERN Developer',
        salary: 19750,
        image: 'https://cdni.rbth.com/rbthmedia/images/web/in-rbth/images/2014-09/top/top1.png',
    },
    {
        id: 12,
        name: 'Bradley Snider',
        age: 44,
        country: 'USA',
        skill: 'Mobile Apps Developer',
        salary: 13525,
        image: 'https://cdn.crello.com/api/media/medium/296539488/stock-photo-young-african-american-programmer-working',
    }
]